fix: cmake -DSTATIC_LINK=ON on Linux
ccache/ccache pull request #1340
Opened 2023-10-19 01:28 UTC by rkitover

Make linking dependent libraries as static a hard requirement when STATIC_LINK is ON, as opposed to the previous behavior of falling back to dynamic libraries.

A side-effect of this is that if only a dynamic zstd/hiredis is available on a system, it will not be found, and the download and build code will be invoked to build a static version from the internet.

Add a general case to handle Linux and similar by linking only libc.

Move the code into cmake/StaticLinkSupport.cmake and include it from the main file.

Fix #1330

2023-10-19 01:30 UTC, rkitover commented
@Flamefire @jrosdahl can you guys take a look and test this out please.

2023-10-20 15:09 UTC, Flamefire requested changes
Works for me:
```
$ ldd /tmp/ebinstall/software/ccache/4.8.3/bin/ccache 
	linux-vdso64.so.1 =>  (0x0000200000050000)
	libm.so.6 => /lib64/libm.so.6 (0x0000200000090000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x0000200000180000)
	libc.so.6 => /lib64/libc.so.6 (0x00002000001c0000)
	/lib64/ld64.so.2 (0x0000200000000000)
```

I'd suggest to fix the string compares as `GNU` might get expanded when unquoted. (E.g. `MSVC` gets expanded to "1" when compiling with VS)

2023-10-20 19:22 UTC, TheNetos commented on cmake/StaticLinkSupport.cmake
> +    if((CMAKE_CXX_COMPILER_ID STREQUAL GNU) OR (CMAKE_CXX_COMPILER_ID STREQUAL Clang))
Maybe it's better like this:
```cmake
if(CMAKE_CXX_COMPILER_ID MATCHES "(GNU|Clang)"))
```

2023-10-20 19:22 UTC, TheNetos commented on cmake/StaticLinkSupport.cmake
> +  if((CMAKE_CXX_COMPILER_ID STREQUAL GNU) OR (CMAKE_CXX_COMPILER_ID STREQUAL Clang))
Maybe it's better like this:
```cmake
if(CMAKE_CXX_COMPILER_ID MATCHES "(GNU|Clang)"))
```

2023-10-20 19:23 UTC, rkitover commented
Fixed, thanks! And thank you for testing!

2023-10-20 19:51 UTC, rkitover commented on cmake/StaticLinkSupport.cmake
> +  if((CMAKE_CXX_COMPILER_ID STREQUAL GNU) OR (CMAKE_CXX_COMPILER_ID STREQUAL Clang))
cmake regexes are case-insensitive

2023-10-20 19:51 UTC, rkitover commented on cmake/StaticLinkSupport.cmake
> +  if((CMAKE_CXX_COMPILER_ID STREQUAL GNU) OR (CMAKE_CXX_COMPILER_ID STREQUAL Clang))
but maybe that's fine here

2023-10-20 19:58 UTC, rkitover commented on cmake/StaticLinkSupport.cmake
> +  if((CMAKE_CXX_COMPILER_ID STREQUAL GNU) OR (CMAKE_CXX_COMPILER_ID STREQUAL Clang))
fixed

2023-10-29 08:28 UTC, merged

2023-10-29 08:28 UTC, jrosdahl commented
Thanks.